import { and, eq, inArray, lte, sql } from 'drizzle-orm';
import type { Executor, Transaction } from '../pool.js';
import { outbox } from '../schema/index.js';

export const OutboxTopic = {
  /** Every operation type shares one topic; the worker resolves the type from PostgreSQL. */
  OPERATION_READY: 'operation.ready',
} as const;

export type OutboxTopic = (typeof OutboxTopic)[keyof typeof OutboxTopic];

export interface OutboxRecord {
  readonly id: string;
  readonly topic: string;
  readonly aggregateType: string;
  readonly aggregateId: string;
  readonly payload: unknown;
  readonly status: string;
  readonly attempts: number;
  readonly availableAt: Date;
  readonly dispatchedAt: Date | null;
  readonly lastError: string | null;
  readonly correlationId: string;
  readonly createdAt: Date;
}

/**
 * Enqueued in the same transaction as the business state change. The payload carries
 * identifiers only, so a stale or replayed message cannot carry stale financial truth.
 */
export async function enqueueOutbox(
  executor: Executor,
  input: {
    topic: OutboxTopic;
    aggregateType: string;
    aggregateId: string;
    payload: Record<string, string>;
    correlationId: string;
  },
): Promise<OutboxRecord> {
  const [row] = await executor.insert(outbox).values(input).returning();
  if (row === undefined) throw new Error('failed to enqueue outbox row');
  return row;
}

/**
 * FOR UPDATE SKIP LOCKED lets several dispatchers drain the outbox concurrently without
 * blocking each other or handing the same row to two of them.
 */
export async function claimPendingOutbox(
  tx: Transaction,
  input: { limit: number; now?: Date },
): Promise<OutboxRecord[]> {
  // available_at is generated by the database, so it must be compared against the
  // database clock. Using the application clock silently starves the outbox whenever
  // the two drift apart (routinely the case with a containerised PostgreSQL).
  const now = input.now ?? sql`now()`;
  const candidates = await tx
    .select({ id: outbox.id })
    .from(outbox)
    .where(and(eq(outbox.status, 'PENDING'), lte(outbox.availableAt, now)))
    .orderBy(outbox.availableAt, outbox.id)
    .limit(input.limit)
    .for('update', { skipLocked: true });

  if (candidates.length === 0) return [];

  const ids = candidates.map((row) => row.id);
  return tx
    .update(outbox)
    .set({ attempts: sql`${outbox.attempts} + 1` })
    .where(inArray(outbox.id, ids))
    .returning();
}

export async function markOutboxDispatched(executor: Executor, ids: string[]): Promise<void> {
  if (ids.length === 0) return;
  await executor
    .update(outbox)
    .set({ status: 'DISPATCHED', dispatchedAt: new Date(), lastError: null })
    .where(inArray(outbox.id, ids));
}

/**
 * Returns a failed row to PENDING with a backoff. Rows are never dropped: the workflow
 * intent lives here, not in Redis.
 */
export async function rescheduleOutbox(
  executor: Executor,
  input: { id: string; error: string; retryAfterMs: number },
): Promise<void> {
  await executor
    .update(outbox)
    .set({
      status: 'PENDING',
      lastError: input.error.slice(0, 1000),
      availableAt: sql`now() + make_interval(secs => ${input.retryAfterMs / 1000})`,
    })
    .where(eq(outbox.id, input.id));
}

export async function countOutboxByStatus(
  executor: Executor,
): Promise<{ status: string; count: number }[]> {
  const rows = await executor
    .select({ status: outbox.status, count: sql<string>`count(*)` })
    .from(outbox)
    .groupBy(outbox.status);
  return rows.map((row) => ({ status: row.status, count: Number(row.count) }));
}

export async function findOutboxForAggregate(
  executor: Executor,
  aggregateId: string,
): Promise<OutboxRecord[]> {
  return executor.select().from(outbox).where(eq(outbox.aggregateId, aggregateId));
}
