import { randomUUID } from 'node:crypto';
import { and, eq, inArray, sql } from 'drizzle-orm';
import type { Executor, Transaction } from '../pool.js';
import { outbox } from '../schema/index.js';

export const OutboxTopic = {
  /** Every operation type shares one topic; the worker resolves the type from PostgreSQL. */
  OPERATION_READY: 'operation.ready',
} as const;

export type OutboxTopic = (typeof OutboxTopic)[keyof typeof OutboxTopic];

export interface OutboxRecord {
  readonly id: string;
  readonly topic: string;
  readonly aggregateType: string;
  readonly aggregateId: string;
  readonly payload: unknown;
  readonly status: string;
  readonly attempts: number;
  readonly availableAt: Date;
  readonly dispatchedAt: Date | null;
  readonly lastError: string | null;
  readonly correlationId: string;
  readonly claimToken: string | null;
  readonly claimExpiresAt: Date | null;
  readonly createdAt: Date;
}

/**
 * Enqueued in the same transaction as the business state change. The payload carries
 * identifiers only, so a stale or replayed message cannot carry stale financial truth.
 */
export async function enqueueOutbox(
  executor: Executor,
  input: {
    topic: OutboxTopic;
    aggregateType: string;
    aggregateId: string;
    payload: Record<string, string>;
    correlationId: string;
  },
): Promise<OutboxRecord> {
  const [row] = await executor.insert(outbox).values(input).returning();
  if (row === undefined) throw new Error('failed to enqueue outbox row');
  return row;
}

const DEFAULT_CLAIM_LEASE_MS = 30_000;

/**
 * Takes ownership of due rows in one statement. The claim is persisted here rather than
 * held as a row lock, because the lock dies at commit and the dispatcher must commit
 * before it talks to Redis. A claim whose lease expires is reclaimable, so a dispatcher
 * that dies mid-cycle strands nothing.
 */
export async function claimPendingOutbox(
  tx: Transaction,
  input: { limit: number; leaseMs?: number; now?: Date },
): Promise<{ claimToken: string; rows: OutboxRecord[] }> {
  const claimToken = randomUUID();
  const leaseSeconds = (input.leaseMs ?? DEFAULT_CLAIM_LEASE_MS) / 1000;
  // available_at is generated by the database, so it must be compared against the
  // database clock. Using the application clock silently starves the outbox whenever
  // the two drift apart (routinely the case with a containerised PostgreSQL).
  const dueAt = input.now ?? sql`now()`;

  const claimed = await tx.execute(sql`
    WITH candidates AS (
      SELECT id FROM outbox
      WHERE (status = 'PENDING' AND available_at <= ${dueAt})
         OR (status = 'CLAIMED' AND claim_expires_at <= now())
      ORDER BY available_at, id
      LIMIT ${input.limit}
      FOR UPDATE SKIP LOCKED
    )
    UPDATE outbox
    SET status = 'CLAIMED',
        claim_token = ${claimToken},
        claim_expires_at = now() + make_interval(secs => ${leaseSeconds}),
        attempts = outbox.attempts + 1
    FROM candidates
    WHERE outbox.id = candidates.id
    RETURNING outbox.*
  `);

  return { claimToken, rows: claimed.rows.map(toOutboxRecord) };
}

/** Only the holder of the claim may complete it; an expired claim has moved on. */
export async function markOutboxDispatched(
  executor: Executor,
  input: { ids: string[]; claimToken: string },
): Promise<void> {
  if (input.ids.length === 0) return;
  await executor
    .update(outbox)
    .set({
      status: 'DISPATCHED',
      dispatchedAt: sql`now()`,
      lastError: null,
      claimToken: null,
      claimExpiresAt: null,
    })
    .where(and(inArray(outbox.id, input.ids), eq(outbox.claimToken, input.claimToken)));
}

/**
 * Returns a failed row to PENDING with a backoff. Rows are never dropped: the workflow
 * intent lives here, not in Redis.
 */
export async function rescheduleOutbox(
  executor: Executor,
  input: { id: string; claimToken: string; error: string; retryAfterMs: number },
): Promise<void> {
  await executor
    .update(outbox)
    .set({
      status: 'PENDING',
      lastError: input.error.slice(0, 1000),
      availableAt: sql`now() + make_interval(secs => ${input.retryAfterMs / 1000})`,
      claimToken: null,
      claimExpiresAt: null,
    })
    .where(and(eq(outbox.id, input.id), eq(outbox.claimToken, input.claimToken)));
}

function toOutboxRecord(row: Record<string, unknown>): OutboxRecord {
  return {
    id: row.id as string,
    topic: row.topic as string,
    aggregateType: row.aggregate_type as string,
    aggregateId: row.aggregate_id as string,
    payload: row.payload,
    status: row.status as string,
    attempts: Number(row.attempts),
    availableAt: row.available_at as Date,
    dispatchedAt: row.dispatched_at as Date | null,
    lastError: row.last_error as string | null,
    correlationId: row.correlation_id as string,
    claimToken: row.claim_token as string | null,
    claimExpiresAt: row.claim_expires_at as Date | null,
    createdAt: row.created_at as Date,
  };
}

export async function countOutboxByStatus(
  executor: Executor,
): Promise<{ status: string; count: number }[]> {
  const rows = await executor
    .select({ status: outbox.status, count: sql<string>`count(*)` })
    .from(outbox)
    .groupBy(outbox.status);
  return rows.map((row) => ({ status: row.status, count: Number(row.count) }));
}

export async function findOutboxForAggregate(
  executor: Executor,
  aggregateId: string,
): Promise<OutboxRecord[]> {
  return executor.select().from(outbox).where(eq(outbox.aggregateId, aggregateId));
}
